export { default as Projects }        from '../features/projects/ProjectList'
export { default as MyTasks }         from '../features/myTasks/MyTasks'
export { default as Tools }           from '../features/tools/Tools'
export { default as Team }            from '../features/team/Team'
export { default as Notifications }   from '../features/notifications/Notifications'
export { default as Procurement }     from '../features/projects/Procurement'
