import { supabase } from '../../lib/supabase'
import { useStore, currencySymbol } from '../../store/useStore'

// ── i18n ─────────────────────────────────────────────────────────────────────
const i18n = {
  ru: {
    monthlyTitle: 'Расчётный лист',
    annualTitle: 'Годовой отчёт',
    accrued: 'Начислено', paid: 'Выплачено', debt: 'К выплате', balance: 'Остаток',
    date: 'Дата', type: 'Тип', qty: 'Кол-во', rate: 'Ставка', sum: 'Сумма',
    shift: 'Смена', hours: 'Часы', perShift: '/смена', perHour: '/ч',
    month: 'Месяц', shiftsHours: 'Смен/Часов',
    total: 'Итого', grandTotal: 'Общий итог',
    annualAccrued: 'Начислено за год', annualPaid: 'Выплачено за год', annualDebt: 'Общий долг',
    noActivity: 'Нет активности за период',
    saveAsPdf: 'Сохранить как PDF', close: 'Закрыть',
    generatedBy: 'Сформировано в',
    months: ['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'],
    shortMonths: ['Янв','Фев','Мар','Апр','Май','Июн','Июл','Авг','Сен','Окт','Ноя','Дек'],
    overpaid: 'Переплата',
  },
  en: {
    monthlyTitle: 'Payroll Report',
    annualTitle: 'Annual Payroll Report',
    accrued: 'Accrued', paid: 'Paid', debt: 'Due', balance: 'Balance',
    date: 'Date', type: 'Type', qty: 'Qty', rate: 'Rate', sum: 'Amount',
    shift: 'Shift', hours: 'Hours', perShift: '/shift', perHour: '/hr',
    month: 'Month', shiftsHours: 'Shifts/Hours',
    total: 'Total', grandTotal: 'Grand Total',
    annualAccrued: 'Accrued this year', annualPaid: 'Paid this year', annualDebt: 'Total debt',
    noActivity: 'No activity for this period',
    saveAsPdf: 'Save as PDF', close: 'Close',
    generatedBy: 'Generated by',
    months: ['January','February','March','April','May','June','July','August','September','October','November','December'],
    shortMonths: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
    overpaid: 'Overpaid',
  },
}

const AVATAR_COLORS = ['#3B82F6','#F59E0B','#10B981','#8B5CF6','#EF4444','#06B6D4']

// ── Helpers ───────────────────────────────────────────────────────────────────
function fmt(n) {
  return Math.round(n).toString().replace(/\B(?=(\d{3})+(?!\d))/g, ' ')
}
function fmtDate(s, lang) {
  if (!s) return ''
  const [y, m, d] = s.split('-')
  return lang === 'en' ? `${m}/${d}/${y}` : `${d}.${m}.${y}`
}
function initials(name) {
  return (name || '?').split(' ').map(w => w[0]).join('').toUpperCase().slice(0, 2)
}
function lastDay(year, month) {
  return new Date(year, month, 0).getDate()
}
function debtStr(val, currSym) {
  if (val > 0)  return `${currSym}${fmt(val)}`
  if (val < 0)  return `+${currSym}${fmt(-val)}`
  return '✓'
}
function debtCls(val) {
  return val > 0 ? 'neg' : val <= 0 ? 'pos' : ''
}

// ── Fetch helpers ─────────────────────────────────────────────────────────────
async function getWorkerIds(profile, projects) {
  let ids = []
  if (projects.length) {
    const { data } = await supabase.from('project_workers').select('worker_id')
      .in('project_id', projects.map(p => p.id))
    ids = [...new Set((data || []).map(r => r.worker_id))]
  }
  if (!ids.length && profile) {
    const { data } = await supabase.from('join_requests').select('worker_id')
      .eq('foreman_id', profile.id).eq('status', 'approved')
    ids = [...new Set((data || []).map(r => r.worker_id))]
  }
  return ids
}

async function fetchPeriodData(workerIds, startDate, endDate) {
  const [{ data: logs }, { data: pays }, { data: profiles }] = await Promise.all([
    supabase.from('work_logs').select('*')
      .in('worker_id', workerIds)
      .gte('log_date', startDate).lte('log_date', endDate)
      .order('log_date'),
    supabase.from('worker_payments').select('*')
      .in('worker_id', workerIds)
      .gte('paid_at', startDate).lte('paid_at', endDate)
      .order('paid_at'),
    supabase.from('profiles').select('id, name, default_rate, rate_type')
      .in('id', workerIds),
  ])
  return { logs: logs || [], pays: pays || [], workers: profiles || [] }
}

// ── Shared CSS ────────────────────────────────────────────────────────────────
const CSS = `
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:system-ui,-apple-system,sans-serif;background:#fff;color:#1C1917;padding:32px}
.wrap{max-width:800px;margin:0 auto}
.top-bar{display:flex;gap:8px;justify-content:flex-end;margin-bottom:24px}
.btn{padding:8px 18px;border-radius:6px;font-size:13px;cursor:pointer;border:none;font-family:inherit;font-weight:500}
.btn-primary{background:#EA580C;color:#fff}
.btn-secondary{background:#F0EEE8;color:#1C1917}
.rpt-header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:28px;padding-bottom:20px;border-bottom:1px solid #E8E4DC;flex-wrap:wrap;gap:16px}
.rpt-title{font-size:18px;font-weight:500;margin-bottom:4px}
.rpt-sub{font-size:12px;color:#A8A29E}
.chips{display:flex;gap:20px;flex-wrap:wrap}
.chip .cl{font-size:10px;color:#A8A29E;text-transform:uppercase;letter-spacing:.5px;margin-bottom:2px}
.chip .cv{font-size:20px;font-weight:500}
.neg{color:#DC2626}.pos{color:#16A34A}
.neg-bg{color:#DC2626;background:#FEE2E2;padding:2px 8px;border-radius:4px}
.pos-bg{color:#16A34A;background:#DCFCE7;padding:2px 8px;border-radius:4px}
.worker-block{margin-bottom:24px;border:1px solid #F0EEE8;border-radius:8px;overflow:hidden}
.w-head{display:flex;align-items:center;gap:12px;padding:14px 16px;background:#F9F8F6;border-bottom:1px solid #E8E4DC;flex-wrap:wrap;gap:10px}
.avatar{width:38px;height:38px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:13px;font-weight:700;color:#fff;flex-shrink:0}
.w-name{font-size:14px;font-weight:500}
.w-rate{font-size:11px;color:#A8A29E}
.w-summary{margin-left:auto;display:flex;gap:16px;text-align:right;flex-wrap:wrap}
.si .sl{font-size:10px;color:#A8A29E;text-transform:uppercase;letter-spacing:.5px}
.si .sv{font-size:14px;font-weight:500}
table{width:100%;border-collapse:collapse}
th{font-size:11px;font-weight:500;text-transform:uppercase;letter-spacing:.5px;color:#A8A29E;text-align:left;padding:10px 16px;border-bottom:1px solid #F0EEE8;background:#FAFAF9}
td{font-size:13px;padding:9px 16px;border-bottom:1px solid #F0EEE8;color:#1C1917}
td.amt{font-weight:500}
td.dim{color:#A8A29E}
tr:last-child td{border-bottom:none}
.dash{border-top:1px dashed #E8E4DC;margin:0 16px}
.totals{padding:12px 16px;background:#F9F8F6}
.trow{display:flex;justify-content:space-between;align-items:center;margin-bottom:5px}
.trow:last-child{margin-bottom:0}
.tl{font-size:12px;color:#A8A29E}
.tv{font-size:13px;font-weight:500}
.pays-list{padding:10px 16px;border-top:1px solid #F0EEE8}
.pay-row{font-size:12px;color:#78716C;padding:4px 0}
.pay-row .pa{color:#16A34A;font-weight:500}
.footer{margin-top:28px;padding:18px;background:#F9F8F6;border-radius:8px;border:1px solid #E8E4DC;display:flex;justify-content:space-between;flex-wrap:wrap;gap:16px}
.footer .fi .fl{font-size:10px;color:#A8A29E;text-transform:uppercase;letter-spacing:.5px;margin-bottom:3px}
.footer .fi .fv{font-size:20px;font-weight:500}
.gen{margin-top:16px;text-align:center;font-size:11px;color:#C4B5A5}
/* Chart */
.chart-wrap{padding:16px 16px 8px;border-bottom:1px solid #F0EEE8}
.bar-chart{display:flex;align-items:flex-end;gap:5px;height:130px}
.bc{flex:1;display:flex;flex-direction:column;align-items:center;gap:3px}
.bt{font-size:8px;color:#A8A29E;width:100%;text-align:center;overflow:hidden;white-space:nowrap}
.bf{width:100%;border-radius:3px 3px 0 0}
.bb{font-size:9px;color:#A8A29E}
/* Annual table */
.ann-table{width:100%;border-collapse:collapse}
.ann-table th{font-size:11px;font-weight:500;text-transform:uppercase;letter-spacing:.5px;color:#A8A29E;text-align:left;padding:8px 16px;border-bottom:1px solid #F0EEE8;background:#FAFAF9}
.ann-table td{font-size:13px;padding:8px 16px;border-bottom:1px solid #F0EEE8}
.ann-table tr.total-row td{font-weight:600;background:#F9F8F6;border-bottom:none}
details summary{cursor:pointer;list-style:none;padding:10px 16px;font-size:12px;color:#A8A29E;border-top:1px solid #F0EEE8}
details summary::-webkit-details-marker{display:none}
@media print{
  body{-webkit-print-color-adjust:exact;print-color-adjust:exact;padding:16px}
  .no-print{display:none!important}
  .worker-block{page-break-inside:avoid}
  .bar-chart{page-break-inside:avoid}
}
`

// ── Monthly HTML builder ──────────────────────────────────────────────────────
function buildMonthlyHTML({ workers, logs, pays, month, year, lang, currSym }) {
  const t   = i18n[lang] || i18n.ru
  const mon = t.months[month - 1]
  const now = new Date().toLocaleDateString(lang === 'ru' ? 'ru-RU' : 'en-US')

  const byW = {}
  for (const w of workers) byW[w.id] = { ...w, logs: [], pays: [] }
  logs.forEach(l => { if (byW[l.worker_id]) byW[l.worker_id].logs.push(l) })
  pays.forEach(p => { if (byW[p.worker_id]) byW[p.worker_id].pays.push(p) })

  const active = Object.values(byW).filter(w => w.logs.length || w.pays.length)
  let gEarned = 0, gPaid = 0

  const blocks = active.map((w, idx) => {
    const earned = w.logs.reduce((s, l) => s + l.value * l.rate, 0)
    const paid   = w.pays.reduce((s, p) => s + Number(p.amount), 0)
    const debt   = earned - paid
    gEarned += earned; gPaid += paid
    const color = AVATAR_COLORS[idx % AVATAR_COLORS.length]
    const rateInfo = w.rate_type === 'hours'
      ? `${currSym}${fmt(w.default_rate || 0)}${t.perHour}`
      : `${currSym}${fmt(w.default_rate || 0)}${t.perShift}`

    const logRows = w.logs.map(l => {
      const typ = l.log_type === 'hours' ? t.hours : t.shift
      const qty = l.log_type === 'hours' ? `${l.value} ч` : `${l.value}`
      const rt  = l.log_type === 'hours' ? `${currSym}${fmt(l.rate)}${t.perHour}` : `${currSym}${fmt(l.rate)}${t.perShift}`
      const note = l.notes ? `<br><small style="color:#A8A29E">${l.notes}</small>` : ''
      return `<tr>
        <td>${fmtDate(l.log_date, lang)}${note}</td>
        <td>${typ}</td><td>${qty}</td>
        <td class="dim">${rt}</td>
        <td class="amt">${currSym}${fmt(l.value * l.rate)}</td>
      </tr>`
    }).join('')

    const payRows = w.pays.map(p =>
      `<div class="pay-row">${fmtDate(p.paid_at, lang)} — <span class="pa">−${currSym}${fmt(p.amount)}</span>${p.notes ? ` — ${p.notes}` : ''}</div>`
    ).join('')

    return `<div class="worker-block">
      <div class="w-head">
        <div class="avatar" style="background:${color}">${initials(w.name)}</div>
        <div><div class="w-name">${w.name || '—'}</div><div class="w-rate">${rateInfo}</div></div>
        <div class="w-summary">
          <div class="si"><div class="sl">${t.accrued}</div><div class="sv">${currSym}${fmt(earned)}</div></div>
          <div class="si"><div class="sl">${t.paid}</div><div class="sv">${currSym}${fmt(paid)}</div></div>
          <div class="si"><div class="sl">${t.debt}</div><div class="sv ${debtCls(debt)}">${debtStr(debt, currSym)}</div></div>
        </div>
      </div>
      ${w.logs.length ? `<table><thead><tr>
        <th>${t.date}</th><th>${t.type}</th><th>${t.qty}</th><th>${t.rate}</th><th>${t.sum}</th>
      </tr></thead><tbody>${logRows}</tbody></table><div class="dash"></div>` : ''}
      <div class="totals">
        <div class="trow"><span class="tl">${t.accrued}</span><span class="tv">${currSym}${fmt(earned)}</span></div>
        <div class="trow"><span class="tl">${t.paid}</span><span class="tv">${currSym}${fmt(paid)}</span></div>
        <div class="trow"><span class="tl">${t.debt}</span><span class="tv ${debt > 0 ? 'neg-bg' : debt < 0 ? 'pos-bg' : 'pos-bg'}">${debtStr(debt, currSym)}</span></div>
      </div>
      ${payRows ? `<div class="pays-list">${payRows}</div>` : ''}
    </div>`
  }).join('')

  const gDebt = gEarned - gPaid

  return `<!DOCTYPE html><html lang="${lang}"><head>
  <meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${t.monthlyTitle} · ${mon} ${year}</title>
  <style>${CSS}</style></head><body>
  <div class="wrap">
    <div class="top-bar no-print">
      <button class="btn btn-primary" onclick="window.print()">${t.saveAsPdf}</button>
      <button class="btn btn-secondary" onclick="window.close()">${t.close}</button>
    </div>
    <div class="rpt-header">
      <div>
        <div class="rpt-title">${t.monthlyTitle} · ${mon} ${year}</div>
        <div class="rpt-sub">tutuu.net · ${now}</div>
      </div>
      <div class="chips">
        <div class="chip"><div class="cl">${t.accrued}</div><div class="cv">${currSym}${fmt(gEarned)}</div></div>
        <div class="chip"><div class="cl">${t.paid}</div><div class="cv">${currSym}${fmt(gPaid)}</div></div>
        <div class="chip"><div class="cl">${t.debt}</div><div class="cv ${debtCls(gDebt)}">${debtStr(gDebt, currSym)}</div></div>
      </div>
    </div>
    ${blocks || `<p style="color:#A8A29E;text-align:center;padding:48px 0">${t.noActivity}</p>`}
    <div class="footer">
      <div class="fi"><div class="fl">${t.grandTotal}</div></div>
      <div class="fi"><div class="fl">${t.accrued}</div><div class="fv">${currSym}${fmt(gEarned)}</div></div>
      <div class="fi"><div class="fl">${t.paid}</div><div class="fv">${currSym}${fmt(gPaid)}</div></div>
      <div class="fi"><div class="fl">${t.debt}</div><div class="fv ${debtCls(gDebt)}">${debtStr(gDebt, currSym)}</div></div>
    </div>
    <div class="gen">${t.generatedBy} tutuu.net</div>
  </div></body></html>`
}

// ── Annual HTML builder ───────────────────────────────────────────────────────
function buildAnnualHTML({ workers, logs, pays, year, lang, currSym }) {
  const t = i18n[lang] || i18n.ru
  const now = new Date().toLocaleDateString(lang === 'ru' ? 'ru-RU' : 'en-US')
  const curMonthIdx = new Date().getFullYear() === year ? new Date().getMonth() : -1

  const byW = {}
  for (const w of workers) byW[w.id] = { ...w, byM: Array.from({length:12}, () => ({logs:[], pays:[]})) }
  logs.forEach(l => { if (byW[l.worker_id]) byW[l.worker_id].byM[parseInt(l.log_date.split('-')[1])-1].logs.push(l) })
  pays.forEach(p => { if (byW[p.worker_id]) byW[p.worker_id].byM[parseInt(p.paid_at.split('-')[1])-1].pays.push(p) })

  // Monthly totals for chart
  const mTotals = Array(12).fill(0)
  Object.values(byW).forEach(w => w.byM.forEach((m, i) => { mTotals[i] += m.logs.reduce((s,l) => s+l.value*l.rate, 0) }))
  const maxT = Math.max(...mTotals, 1)

  const chart = `<div class="chart-wrap">
    <div class="bar-chart">${mTotals.map((v, i) => {
      const h = Math.max(Math.round((v / maxT) * 110), v > 0 ? 4 : 2)
      const cur = i === curMonthIdx
      return `<div class="bc">
        <div class="bt">${v > 0 ? fmt(v) : ''}</div>
        <div class="bf" style="height:${h}px;background:${cur ? '#EA580C' : '#E8E4DC'}"></div>
        <div class="bb">${t.shortMonths[i]}</div>
      </div>`
    }).join('')}</div>
  </div>`

  const active = Object.values(byW).filter(w => w.byM.some(m => m.logs.length || m.pays.length))
  let gEarned = 0, gPaid = 0

  const blocks = active.map((w, idx) => {
    const tEarned = w.byM.reduce((s, m) => s + m.logs.reduce((ss,l) => ss+l.value*l.rate, 0), 0)
    const tPaid   = w.byM.reduce((s, m) => s + m.pays.reduce((ss,p) => ss+Number(p.amount), 0), 0)
    const tDebt   = tEarned - tPaid
    gEarned += tEarned; gPaid += tPaid
    const color   = AVATAR_COLORS[idx % AVATAR_COLORS.length]
    const rateInfo = w.rate_type === 'hours'
      ? `${currSym}${fmt(w.default_rate||0)}${t.perHour}`
      : `${currSym}${fmt(w.default_rate||0)}${t.perShift}`

    const mRows = w.byM.map((m, i) => {
      const mE = m.logs.reduce((s,l) => s+l.value*l.rate, 0)
      const mP = m.pays.reduce((s,p) => s+Number(p.amount), 0)
      const mD = mE - mP
      if (!mE && !mP) return ''
      const qty = w.rate_type === 'hours'
        ? `${m.logs.reduce((s,l)=>s+l.value,0)} ч`
        : `${m.logs.reduce((s,l)=>s+l.value,0)}`
      return `<tr>
        <td>${t.months[i]}</td>
        <td>${m.logs.length ? qty : '—'}</td>
        <td>${mE ? `${currSym}${fmt(mE)}` : '—'}</td>
        <td>${mP ? `<span class="pos">${currSym}${fmt(mP)}</span>` : '—'}</td>
        <td>${mD > 0 ? `<span class="neg">${currSym}${fmt(mD)}</span>` : mD < 0 ? `<span class="pos">+${currSym}${fmt(-mD)}</span>` : '<span class="pos">✓</span>'}</td>
      </tr>`
    }).filter(Boolean).join('')

    const totQty = w.rate_type === 'hours'
      ? `${w.byM.reduce((s,m)=>s+m.logs.reduce((ss,l)=>ss+l.value,0),0)} ч`
      : `${w.byM.reduce((s,m)=>s+m.logs.reduce((ss,l)=>ss+l.value,0),0)}`

    return `<div class="worker-block">
      <div class="w-head">
        <div class="avatar" style="background:${color}">${initials(w.name)}</div>
        <div><div class="w-name">${w.name||'—'}</div><div class="w-rate">${rateInfo}</div></div>
        <div class="w-summary">
          <div class="si"><div class="sl">${t.accrued}</div><div class="sv">${currSym}${fmt(tEarned)}</div></div>
          <div class="si"><div class="sl">${t.paid}</div><div class="sv">${currSym}${fmt(tPaid)}</div></div>
          <div class="si"><div class="sl">${t.debt}</div><div class="sv ${debtCls(tDebt)}">${debtStr(tDebt, currSym)}</div></div>
        </div>
      </div>
      <details>
        <summary>▸ ${t.months[0]} – ${t.months[11]} · подробно</summary>
        <table class="ann-table">
          <thead><tr>
            <th>${t.month}</th><th>${t.shiftsHours}</th>
            <th>${t.accrued}</th><th>${t.paid}</th><th>${t.balance}</th>
          </tr></thead>
          <tbody>
            ${mRows}
            <tr class="total-row">
              <td>${t.total}</td><td>${totQty}</td>
              <td>${currSym}${fmt(tEarned)}</td>
              <td class="pos">${currSym}${fmt(tPaid)}</td>
              <td class="${debtCls(tDebt)}">${debtStr(tDebt, currSym)}</td>
            </tr>
          </tbody>
        </table>
      </details>
    </div>`
  }).join('')

  const gDebt = gEarned - gPaid

  return `<!DOCTYPE html><html lang="${lang}"><head>
  <meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${t.annualTitle} · ${year}</title>
  <style>${CSS}</style></head><body>
  <div class="wrap">
    <div class="top-bar no-print">
      <button class="btn btn-primary" onclick="window.print()">${t.saveAsPdf}</button>
      <button class="btn btn-secondary" onclick="window.close()">${t.close}</button>
    </div>
    <div class="rpt-header">
      <div>
        <div class="rpt-title">${t.annualTitle} · ${year}</div>
        <div class="rpt-sub">tutuu.net · ${now}</div>
      </div>
      <div class="chips">
        <div class="chip"><div class="cl">${t.annualAccrued}</div><div class="cv">${currSym}${fmt(gEarned)}</div></div>
        <div class="chip"><div class="cl">${t.annualPaid}</div><div class="cv">${currSym}${fmt(gPaid)}</div></div>
        <div class="chip"><div class="cl">${t.annualDebt}</div><div class="cv ${debtCls(gDebt)}">${debtStr(gDebt, currSym)}</div></div>
      </div>
    </div>
    ${chart}
    ${blocks || `<p style="color:#A8A29E;text-align:center;padding:48px 0">${t.noActivity}</p>`}
    <div class="footer">
      <div class="fi"><div class="fl">${t.grandTotal} ${year}</div></div>
      <div class="fi"><div class="fl">${t.accrued}</div><div class="fv">${currSym}${fmt(gEarned)}</div></div>
      <div class="fi"><div class="fl">${t.paid}</div><div class="fv">${currSym}${fmt(gPaid)}</div></div>
      <div class="fi"><div class="fl">${t.debt}</div><div class="fv ${debtCls(gDebt)}">${debtStr(gDebt, currSym)}</div></div>
    </div>
    <div class="gen">${t.generatedBy} tutuu.net</div>
  </div></body></html>`
}

// ── Public API ────────────────────────────────────────────────────────────────
export async function generateMonthlyReport(month, year) {
  // Must open window synchronously (before any await) — mobile Safari blocks popup if called after async
  const w = window.open('', '_blank')
  if (!w) { alert('Разрешите открытие новых вкладок в браузере'); return }
  w.document.write('<html><body style="font-family:system-ui;padding:32px;color:#888">Загрузка...</body></html>')

  const { profile, projects } = useStore.getState()
  const lang    = localStorage.getItem('tutuu_lang') || 'ru'
  const currSym = currencySymbol(profile?.currency)

  const workerIds = await getWorkerIds(profile, projects)
  if (!workerIds.length) { w.document.write('<html><body style="font-family:system-ui;padding:32px">Нет рабочих</body></html>'); return }

  const start = `${year}-${String(month).padStart(2,'0')}-01`
  const end   = `${year}-${String(month).padStart(2,'0')}-${String(lastDay(year, month)).padStart(2,'0')}`

  const { logs, pays, workers } = await fetchPeriodData(workerIds, start, end)
  const html = buildMonthlyHTML({ workers, logs, pays, month, year, lang, currSym })

  w.document.open()
  w.document.write(html)
  w.document.close()
}

export async function generateAnnualReport(year) {
  // Must open window synchronously (before any await) — mobile Safari blocks popup if called after async
  const w = window.open('', '_blank')
  if (!w) { alert('Разрешите открытие новых вкладок в браузере'); return }
  w.document.write('<html><body style="font-family:system-ui;padding:32px;color:#888">Загрузка...</body></html>')

  const { profile, projects } = useStore.getState()
  const lang    = localStorage.getItem('tutuu_lang') || 'ru'
  const currSym = currencySymbol(profile?.currency)

  const workerIds = await getWorkerIds(profile, projects)
  if (!workerIds.length) { w.document.write('<html><body style="font-family:system-ui;padding:32px">Нет рабочих</body></html>'); return }

  const { logs, pays, workers } = await fetchPeriodData(workerIds, `${year}-01-01`, `${year}-12-31`)
  const html = buildAnnualHTML({ workers, logs, pays, year, lang, currSym })

  w.document.open()
  w.document.write(html)
  w.document.close()
}
